version: '3.5'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

services:

  webapp:
    build: ./webapp
    container_name: webapp
    environment:
      - MONGODB_ADDRESS=${MONGODB_ADDRESS}
      - ES_HOST=${ES_HOST}
      - ES_PORT=${ES_PORT}
    restart: always
    ports:
      - 8000:8000
    networks:
      - backend
    depends_on:
      - mongo
      - elasticsearch

  mongo:
    build: ./mongo
    container_name: mongo
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - ${DATA_PATH_HOST}/mongo:/data/db
      - ${DATA_PATH_HOST}/mongo_config:/data/configdb
    networks:
      - backend

  influxdb:
    image: influxdb:1.7
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
      - "2003:2003"
#    env_file:
#      - 'env.influxdb'
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/influxdb/data
      - ${DATA_PATH_HOST}/influxdb:/var/lib/influxdb
    networks:
      - backend

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/etc/telegraf/docker.sock
    depends_on:
      - influxdb
    links:
      - influxdb
    networks:
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource,grafana-piechart-panel
    ports:
      - "3000:3000"
    user: "0"
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/grafana/data; chown 472:472 /srv/docker/grafana/data
      - ${DATA_PATH_HOST}/grafana:/var/lib/grafana
    links:
      - influxdb
    depends_on:
      - influxdb
    networks:
      - backend

  elasticsearch:
    build:
      context: ./elasticsearch
      args:
        - ELK_VERSION=${ELK_VERSION}
    container_name: elasticsearch
    volumes:
      - ${DATA_PATH_HOST}/elasticsearch:/usr/share/elasticsearch/data
    environment:
      - cluster.name=test-cluster
      - node.name=test-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.initial_master_nodes=test-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "${ELASTICSEARCH_HOST_HTTP_PORT}:9200"
      - "${ELASTICSEARCH_HOST_TRANSPORT_PORT}:9300"
    networks:
      - backend

volumes:
  mongo:
    driver: ${VOLUMES_DRIVER}
  elasticsearch:
    driver: ${VOLUMES_DRIVER}
